var d=this;function e(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function g(a,b){return a<b?-1:a>b?1:0};var h,k,l,m;function n(){return d.navigator?d.navigator.userAgent:null}function p(){return d.navigator}m=l=k=h=!1;var q;if(q=n()){var aa=p();h=0==q.indexOf("Opera");k=!h&&-1!=q.indexOf("MSIE");(l=!h&&-1!=q.indexOf("WebKit"))&&q.indexOf("Mobile");m=!h&&!l&&"Gecko"==aa.product}var r=h,u=k,v=m,w=l,x,y=p();x=y&&y.platform||"";x.indexOf("Mac");x.indexOf("Win");x.indexOf("Linux");p()&&(p().appVersion||"").indexOf("X11");var z=n();z&&z.indexOf("Android");z&&z.indexOf("iPhone");z&&z.indexOf("iPad");
function A(){var a=d.document;return a?a.documentMode:void 0}var C;a:{var D="",E;if(r&&d.opera)var F=d.opera.version,D="function"==typeof F?F():F;else if(v?E=/rv\:([^\);]+)(\)|;)/:u?E=/MSIE\s+([^\);]+)(\)|;)/:w&&(E=/WebKit\/(\S+)/),E)var G=E.exec(n()),D=G?G[1]:"";if(u){var H=A();if(H>parseFloat(D)){C=String(H);break a}}C=D}var I={};
function J(a){var b;if(!(b=I[a])){b=0;for(var c=String(C).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),L=Math.max(c.length,f.length),B=0;0==b&&B<L;B++){var ba=c[B]||"",ca=f[B]||"",da=RegExp("(\\d*)(\\D*)","g"),ea=RegExp("(\\d*)(\\D*)","g");do{var s=da.exec(ba)||["","",""],t=ea.exec(ca)||["","",""];if(0==s[0].length&&0==t[0].length)break;b=g(0==s[1].length?0:parseInt(s[1],10),0==t[1].length?0:parseInt(t[1],10))||g(0==s[2].length,0==t[2].length)||
g(s[2],t[2])}while(0==b)}b=I[a]=0<=b}return b}var K=d.document,fa=K&&u?A()||("CSS1Compat"==K.compatMode?parseInt(C,10):5):void 0;!v&&!u||u&&u&&9<=fa||v&&J("1.9.1");u&&J("9");u&&J("9");!w||J("528");v&&J("1.9b")||u&&J("8")||r&&J("9.5")||w&&J("528");v&&!J("8")||u&&J("9");function M(){}M.h=function(){M.j||(M.j=new M)};M.h();function N(){}N.prototype.m=null;N.prototype.b=null;var O={},P=null;function Q(a){P||(P=new N,O[""]=P);var b;if(!(b=O[a])){b=new N;var c=a.lastIndexOf("."),f=a.substr(c+1),c=Q(a.substr(0,c));c.b||(c.b={});c.b[f]=b;b.m=c;O[a]=b}return b};function R(a){this.l=[];this.i={};if(a)for(var b=0,c;c=a[b];b++)this.add(c)}R.prototype.add=function(a){this.l.push(a)};R.prototype.indexOf=function(a){return this.i[a]};function S(){R.call(this)}(function(){function a(){}a.prototype=R.prototype;S.p=R.prototype;S.prototype=new a})();S.prototype.add=function(){throw Error("Can't add to EmptyNodeList");};Q("goog.ds");function T(a){a&&U(this,a)}function U(a,b,c,f,L){a.o=b;f||L||(e(b,ga)&&(b=b.substring(0,b.length-1)),e(b,"()")&&(e(b,V)||e(b,W)||e(b,X))&&(f=b.lastIndexOf(ha),-1!=f?(a.c=b.substring(f+1),b=b.substring(0,f)):(a.c=b,b=Y),a.c==W&&(a.n=!0)));a.a=c||b.split("/");a.f=a.a.length;a.k=a.a[a.f-1];a.e=a.a[0];1==a.f?(a.d=a,a.g=0==b.lastIndexOf("$",0)):(b=a.e||null.join("/"),c=Z[b],null==c&&(c=new T,U(c,b,null,a,null),Z[b]=c),a.d=c,a.g=a.d.g,a.e=a.d.e)}T.prototype.a=[];T.prototype.f=null;T.prototype.k=null;
T.prototype.c=null;function $(a){var b=Z[a];null==b&&(b=new T(a),Z[a]=b)}var Z={},ha="/",Y=".",V="name()",W="count()",X="position()",ga="?";$(Y);$("*|text()");$("*");$("@*");$(V);$(W);$(X);new S;/*

 Copyright (c) 2012 Soichi Takamura (http://stakam.net/).

 Dual licensed under the MIT and GPL licenses:
   http://www.opensource.org/licenses/mit-license.php
   http://www.gnu.org/licenses/gpl.html
*/

